WebParser.Web/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using WebParser.Web.Areas.HelpPage.ModelDescriptions;

namespace WebParser.Web.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

WebParser.Web/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebParser.Web.Areas.HelpPage.ModelDescriptions;
using WebParser.Web.Areas.HelpPage.Models;

namespace WebParser.Web.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

WebParser.Web/Views/Apartments/Index.cshtml
@{
  ViewBag.Title = "Объявления";
  Layout = "~/Views/Shared/_ClientApplicationLayout.cshtml";
}

WebParser.Web/Views/ArticlesGroup/Index.cshtml
@using Kendo.Mvc.UI
@using WebParser.Common.Mappers
@using WebParser.Controllers.Mappers
@using WebParser.Controllers.ViewModels.ArticleGroup
@using WebParser.Controllers.ViewModels.Shared
@using WebParser.Controllers.ViewModels.Site
@using WebParser.Web.Utilities
@model ItemViewModel[]

@{
  ViewBag.Title = "Article Groups";
}

<ul class="breadcrumb">
  <li>
    <i class="icon-home"></i>
    <a href="/">Home</a>
    <i class="icon-angle-right"></i>
  </li>
  <li>@Html.ActionLink("Article Groups", "Index")</li>
</ul>

<div class="js-article-group-view"
     data-create-article-group-url="@Url.Action("CreateArticlesGroup", "ArticlesGroup")"
     data-edit-article-group-url="@Url.Action("EditArticlesGroup", "ArticlesGroup")"
     data-delete-articles-group-url="@Url.Action("DeleteArticlesGroup", "ArticlesGroup")"
     data-preview-parsing-result-url="@Url.Action("PreviewParsingResult", "ArticlesGroup")">

  <div class="js-content-container">
    <div class="row-fluid">
      
      <div class="box span6">
        <div class="box-header">
          <h2>Choose Site</h2>
        </div>

        <div class="box-content">
          @(Html.Kendo().DropDownList()
              .Name("sites-dropdown")
              .BindTo(Model)
              .DataTextField("Name")
              .DataValueField("Id"))
        </div>
      </div>

    </div>

    <div class="row-fluid">
      <div class="box span12">
        <div class="box-header">
          <h2>Avalibale Article Groups</h2>

          <div class="box-icon">
            <a href="#" class="btn-setting js-add-articles-group"><i class="halflings-icon plus"></i>Add Article Group</a>
          </div>
        </div>

        <div class="box-content">
          @Html.Partial("_ErrorNotification")

          @(Html.Kendo()
              .Grid<ArticlesGroupItemViewModel>()
              .Name("article-group-grid")
              .HtmlAttributes(new { @Class= "table table-striped table-bordered bootstrap-datatable datatable dataTable" })
              .AutoBind(false)
              .Pageable(x => x.ButtonCount(5).PageSizes(new[] { 5, 10, 20, 50 }))
              .Columns(c =>
              {
                c.Bound(x => x.InternalName);
                c.Bound(x => x.PublicName);
                c.Template(@<text></text>).ClientTemplate(Html.Partial("_ArticlesGroupButtons").ToString());
              })
              .DataSource(read => read
              .Ajax()
              .AutoSync(false)
              .Read(y => y
                .Action("GetArticleGroupsBySite", "ArticlesGroup")
                .Type(HttpVerbs.Post)
                .Data("application.additionalDataHandlers.getHandler('onArticleGroupsAdditionalData')"))))
        </div>
      </div>
    </div>
  </div>

  <div id="js-article-group-placeholder"></div>

</div>

@section templates
{
  @Html.Action("SearchRuleTemplate", "Template")
  @Html.ArticlesGroupTemplate()
  @Html.Partial("~/Views/Shared/_PreviewParsingResultTemplate.cshtml")
  @Html.Partial("~/Views/ArticlesGroup/_FoundArticleLinksTemplate.cshtml")
  @Html.Partial("~/Views/ParsedContent/_Gallery.cshtml")
}

WebParser.Web/Views/ArticlesGroup/_ArticlePostedDateTab.cshtml
<div class="js-article-posted-date-search-rule-view">

  <div class="page-header">
    <h2>
      Setup Search Rule<small> to find Article Posted Date. This Date will be used for sorting in Web Api.</small>
    </h2>
    <br/>
    <div class="controls">
      <label class="control-label">
        <input name="posted-date-switcher" type="radio" value="need-to-configure">I want to configure Article Posted Date
      </label>
      <label class="control-label">
        <input name="posted-date-switcher" type="radio" value="dont-need-to-configured">I do not need to configure Article Posted Date
      </label>
    </div>
  </div>

  <div class="js-search-rules-container">
  </div>
</div>

WebParser.Web/Views/ArticlesGroup/_ArticleSearchRulesTab.cshtml
<div class="js-article-search-rules-view">

  <div class="page-header">
    <h2>
      Setup Search Rules<small> to find interesting fields of Article.</small>
    </h2>
    <br/>
    <h2>
      Provided Field Name<small> will be used as Article Property Name with found content in Web Api.</small>
    </h2>

  </div>

  @Html.Partial("_ErrorNotification")

  <div class="js-search-rules-container">
  </div>

  @*<button type="button" class="btn js-add-searchRule">Add Search Rule</button>*@
</div>

WebParser.Web/Views/ArticlesGroup/_ArticlesGroupButtons.cshtml
<a class="btn btn-info js-repeat-article-group" data-id="#=Id#" title="Repeat Article Group" >
  <i class="halflings-icon white repeat"></i>
</a>

@Html.Partial("_EditDelete")

WebParser.Web/Views/ArticlesGroup/_ArticlesGroupSettingTab.cshtml
@using System.Linq.Expressions
@using Kendo.Mvc.UI
@using WebParser.Common
@using WebParser.Controllers.ViewModels.ArticleGroup;

@model EditArticlesGroupModel

@helper NumericTextBox(Expression<Func<EditArticlesGroupModel, int>> expression, int step, int min, int max, string value)
{
  <div class="control-group">
    @Html.LabelFor(expression, new
    {
      @class = "control-label"
    })
    <div class="controls">
      @(Html.Kendo()
            .NumericTextBoxFor(expression)
            .Step(step)
            .Format("#")
            .Min(min)
            .Max(max)
            .HtmlAttributes(new { @Value = value })
            .ToClientTemplate())
      @Html.ValidationMessageFor(expression)
    </div>
  </div>
}

@helper NumericTextBox(Expression<Func<EditArticlesGroupModel, int?>> expression, int step, int? min, int max, string value)
{
  <div class="control-group">
    @Html.LabelFor(expression, new
    {
      @class = "control-label"
    })
    <div class="controls">
      @(Html.Kendo()
          .NumericTextBoxFor(expression)
          .Step(step)
          .Format("#")
          .Min(min)
          .Max(max)
          .HtmlAttributes(new { @Value = value })
          .ToClientTemplate())
      @Html.ValidationMessageFor(expression)
    </div>
  </div>
}

@helper TextBox(Expression<Func<EditArticlesGroupModel, string>> expression, string value)
{
  <div class="control-group">
    @Html.LabelFor(expression, new
    {
      @Class = "control-label"
    })
    <div class="controls">
      @Html.TextBoxFor(expression, new { @Value = value })
      @Html.ValidationMessageFor(expression)
    </div>
  </div>
}

<div class="page-header">
  <h2>
    Provide Articles Group Name and Links<small> for downloading content where Links To Articles can be found.</small>
  </h2>
</div>

<form class="form-horizontal js-article-group-form js-validateble-form" action="{{= action }}" method="post">
  {{ if(showAsEdit){ }}
  <input data-val="true" data-val-number="The field Id must be a number." data-val-required="The Id field is required." id="Id" name="Id" type="hidden" value="{{= id }}" />
  {{ } }}

  <input data-val="true" data-val-number="The field SiteId must be a number." data-val-required="The SiteId field is required." id="SiteId" name="SiteId" type="hidden" value="{{= siteId }}"/>

  <fieldset>
    @TextBox(x => x.InternalName, "{{= internalName }}")
    @TextBox(x => x.PublicName, "{{= publicName }}")

    <div class="js-links-format-type-section">
      <div class="control-group">
        @Html.LabelFor(x => x.LinksFormatType, new
        {
          @class = "control-label",
        })

        <div class="controls">
          <label class="control-label">
            <input id="LinksFormat-SpecificLinks" name="LinksFormatType" type="radio" {{ if(showSpecificLinks){ }} checked="checked" {{ } }} value="SpecificLinks">Specific Links
          </label>

          <label class="control-label">
            <input id="LinksFormat-LinksFormat" name="LinksFormatType" type="radio" {{ if(showLinksFormat){ }} checked="checked" {{ } }} value="LinksFormat">Links Format
          </label>

          <label class="control-label">
            <input id="LinksFormat-LinksFile" name="LinksFormatType" type="radio" {{ if(showLinksFile){ }} checked="checked" {{ } }} value="LinksFile">Links File
          </label>

          @Html.ValidationMessageFor(x => x.LinksFormatType)
        </div>
      </div>

      <div class="control-group js-specific-links-section" {{ if(!showSpecificLinks){ }} style="display: none" {{ } }}>
        @Html.Label("Links", "Links", new
        {
          @class = "control-label"
        })
        <div class="controls" id="js-links-control"></div>
        @Html.ValidationMessageFor(x => x.Links, string.Empty, new { @Class = "field-validation-valid controls" })
      </div>

      <div class="js-links-format-section" {{ if(!showLinksFormat){ }} style="display: none" {{ } }}>
        <div class="control-group">
          @Html.LabelFor(x => x.LinksFormat, new
          {
            @Class = "control-label"
          })
          <div class="controls">
            @Html.TextBoxFor(x => x.LinksFormat, new { @Value = "{{= linksFormat }}", @Class = "links-format", placeholder = "http://www.example.com/category/subcategory?page={page}" })
            @Html.ValidationMessageFor(x => x.LinksFormat)
          </div>
        </div>

        <div class="control-group">
          @Html.LabelFor(x => x.StartPage, new
          {
            @class = "control-label"
          })
          <div class="controls">
            @(Html.Kendo()
                      .NumericTextBoxFor(x => x.StartPage)
                      .Step(1)
                      .Format("#")
                      .Min(1)
                      .Max(100)
                      .ToClientTemplate())
            @Html.ValidationMessageFor(x => x.StartPage)
          </div>

        </div>
        <div class="control-group">
          @Html.LabelFor(x => x.StepSize, new
          {
            @class = "control-label"
          })
          <div class="controls">
            @(Html.Kendo()
                      .NumericTextBoxFor(x => x.StepSize)
                      .Step(1)
                      .Format("#")
                      .Min(1)
                      .Max(100000)
                      .ToClientTemplate())
            @Html.ValidationMessageFor(x => x.StepSize)
          </div>
        </div>
      </div>

      <div class="js-upload-links-file" {{ if(!showLinksFile){ }} style="display: none" {{ } }}>

        @Html.Label("LinksFile", "Choose File With Links", new
        {
          @class = "control-label",
        })

        <div class="controls">
          @Html.HiddenFor(x => x.LinksFileId, new { @Value = "{{= linksFileId }}" })

          <input type="file" name="linksFile" id="linksFile" />

          @Html.ValidationMessageFor(x => x.LinksFileId)
        </div>

      </div>

      <div class="control-group">
        @Html.LabelFor(x => x.VkGroupId, new
        {
          @Class = "control-label"
        })
        <div class="controls">
          @Html.TextBoxFor(x => x.VkGroupId, new { @Value = "{{= vkGroupId }}" })
          @Html.ValidationMessageFor(x => x.VkGroupId)
        </div>
      </div>

      <div class="control-group">
        @Html.LabelFor(x => x.VkTopicId, new
        {
          @Class = "control-label"
        })
        <div class="controls">
          @Html.TextBoxFor(x => x.VkTopicId, new { @Value = "{{= vkTopicId }}" })
          @Html.ValidationMessageFor(x => x.VkTopicId)
        </div>
      </div>

      <div class="control-group">
        @Html.LabelFor(x => x.VkTopicGroupId, new
        {
          @Class = "control-label"
        })
        <div class="controls">
          @Html.TextBoxFor(x => x.VkTopicGroupId, new { @Value = "{{= vkTopicGroupId }}" })
          @Html.ValidationMessageFor(x => x.VkTopicGroupId)
        </div>
      </div>

      <div class="control-group">
        @Html.LabelFor(x => x.LinksToArticlesSearchRuleSpiderTypeId, new
        {
          @class = "control-label",
        })
        <div class="controls">
          @(Html.Kendo()
                    .DropDownListFor(x => x.LinksToArticlesSearchRuleSpiderTypeId)
                    .BindTo(Model.SpiderTypes)
                    .DataValueField("Id")
                    .DataTextField("Name")
                    .HtmlAttributes(new { @Value = "{{= linksToArticlesSearchRuleSpiderTypeId }}" })
                    .ToClientTemplate()
          )
          @Html.ValidationMessageFor(x => x.LinksToArticlesSearchRuleSpiderTypeId)
        </div>
      </div>

      <div class="control-group">
        @Html.LabelFor(x => x.SpiderTypeId, new
        {
          @class = "control-label",
        })
        <div class="controls">
          @(Html.Kendo()
                    .DropDownListFor(x => x.SpiderTypeId)
                    .BindTo(Model.SpiderTypes)
                    .DataValueField("Id")
                    .DataTextField("Name")
                    .HtmlAttributes(new { @Value = "{{= spiderTypeId }}" })
                    .ToClientTemplate()
          )
          @Html.ValidationMessageFor(x => x.SpiderTypeId)
        </div>
      </div>

      <div class="control-group">
        @Html.LabelFor(x => x.SpiderDoNotLoadImages, new
        {
          @class = "control-label",
        })
        <div class="controls">
          <input data-val="true" data-val-required="@(Html.NameFor(x => x.SpiderDoNotLoadImages)) field is required." id="@Html.NameFor(x => x.SpiderDoNotLoadImages)" name="@Html.NameFor(x => x.SpiderDoNotLoadImages)" type="checkbox" value="true" {{ if(spiderDoNotLoadImages){ }} checked='checked' {{ } }} />
          <input name="@Html.NameFor(x => x.SpiderDoNotLoadImages)" type="hidden" value="false" />
        </div>
      </div>

      @NumericTextBox(x => x.BatchSize, 1, 1, 100, "{{= batchSize }}")
      @NumericTextBox(x => x.BatchDelayInSeconds, 10, 0, 60 * 60 * 24, "{{= batchDelayInSeconds }}")
      @NumericTextBox(x => x.DownloadFileDelayInMillseconds, 100, 0, 1000 * 60 * 60, "{{= downloadFileDelayInMillseconds }}")

      @NumericTextBox(x => x.WaitMilliseconds, 100, null, 100000, "{{= waitMilliseconds }}")

      @TextBox(x => x.TwitterConsumerKey, "{{= twitterConsumerKey }}")
      @TextBox(x => x.TwitterConsumerSecret, "{{= twitterConsumerSecret }}")
      @TextBox(x => x.TwitterAccessToken, "{{= twitterAccessToken }}")
      @TextBox(x => x.TwitterAccessTokenSecret, "{{= twitterAccessTokenSecret }}")

    </div>

  </fieldset>
</form>

WebParser.Web/Views/ArticlesGroup/_ArticlesGroupTemplate.cshtml
@using WebParser.Controllers.ViewModels.ArticleGroup
@model WebParser.Controllers.ViewModels.ArticleGroup.EditArticlesGroupModel

<script type="text/x-kendo-template" id="js-article-group-template">
  <div class="row-fluid js-article-group-settings-container">
    <div class="box span12">
      <div class="box-header" data-original-title>
        <h2>
          <i class="halflings-icon edit"></i><span class="break"></span>{{= text }} Article Group
        </h2>
      </div>
      <div class="box-content">
        
        @Html.ValidationSummary()

        <div class="k-content js-validateble-area-container">
          <div id="articlesGroupSettings">
            <ul>
              <li class="k-state-active">
                Articles Group Setting
              </li>
              <li>
                Links To Articles
              </li> 
              <li>
                Article Search Rules
              </li>
            </ul>
            <div>
              @Html.Partial("~/Views/ArticlesGroup/_ArticlesGroupSettingTab.cshtml", Model)
            </div>
            <div>
              @Html.Partial("~/Views/ArticlesGroup/_LinksToArticlesTab.cshtml")
            </div>
            <div>
              @Html.Partial("~/Views/ArticlesGroup/_ArticleSearchRulesTab.cshtml")
            </div>
          </div>
        </div>
        
        <div class="form-actions">
          <button type="button" class="btn btn-primary js-submit-button js-edit-articles-group-result">{{= text }}</button>
                                                           
          <button class="btn btn-info js-submit-button js-preview-parsing-result " title="Preview Parsing Result">
            <i class="halflings-icon white play"></i>
          </button>

          <button type="reset" class="btn js-cancel-button">Cancel</button>
        </div>
      
      </div>
    </div>
  </div> 
  
  <div id="js-preview-parsing-result-placeholder"></div>
  
  <div id="js-article-group-links-placeholder"></div>
  
</script>

WebParser.Web/Views/ArticlesGroup/_FoundArticleLinksTemplate.cshtml
<script type="text/x-kendo-template" id="js-found-article-links-template">
  <div class="row-fluid">
    <div class="box span12">
      <div class="box-header" data-original-title="">
        <h2>Found links</h2>
      </div>

      <div class="box-content">

        <div class="priority low"><span>FoundArticleLinks length: {{= FoundArticleLinks.length }}</span></div>

        <div class="task low">
          <div class="desc">
            <div>
              <pre>{{= FoundArticleLinks.join('\n') }}</pre>
            </div>
          </div>
        </div>

        <div class="clearfix">
        </div>

      </div>
    </div>
  </div>

</script>

WebParser.Web/Views/ArticlesGroup/_LinksToArticlesTab.cshtml
<div class="js-links-to-articles-search-rule-view">

  <div class="page-header">
    <h2>
      Setup Search Rule<small> to find Links To Articles.</small>
    </h2>
  </div>

  <div class="js-search-rules-container">
  </div>
</div>

WebParser.Web/Views/Forbidden/Index.cshtml
@{
    ViewBag.Title = "Доступ закончился";
    Layout = "~/Views/Shared/_ClientApplicationLayout.cshtml";
}

WebParser.Web/Views/Forbidden/WaitingForPayment.cshtml
@using WebParser.Common.Extensions
@using WebParser.Controllers.Mappers
@using WebParser.Web.Utilities
@model WebParser.Controllers.ViewModels.Forbidden.WaitingForPaymentViewModel

@{
    Layout = "~/Views/Shared/_AccountLayout.cshtml";
    ViewBag.Title = "Оплата завершена";
}

<h2>@ViewBag.Title</h2>

<p>
  Ваш платеж успешно завершен и обрабатывается. Это может занять не более нескольких минут. Обновите страницу, чтобы продолжить пользоваться сайтом.
</p>

<p>Успехов в поиске лучшего жилья!</p>

<p>
  Если по истечении 5 минут Вы все еще видите эту страницу напишите нам письмо на почту <a href="mailto:@Model.SupportEmail">@Model.SupportEmail</a> со следующей информацией:
</p>

<ul>
  <li>Ваш идентификатор: @Model.UserIdentity</li>
  <li>Время оплаты</li>
  <li>Cумма оплаты</li>
</ul>

<h4>Пример письма:</h4>

<address>
  Идентификатор: @Model.UserIdentity<br />
  Время оплаты: @DateTime.Now.ToStringInvariant(ViewModelMapper.NumericDateTimeFormat)<br />
  Cумма оплаты: 290
</address>

<address>
  <strong>Поддержка:</strong> <a href="mailto:@Model.SupportEmail">@Model.SupportEmail</a><br/>
</address>

@section Scripts {
  @MetricsHelper.MetricGoalForPage("waiting-for-payment")
}

WebParser.Web/Views/ParsedContent/_ArticleButtons.cshtml
@Html.Partial("_View")

<a class="btn btn-mini btn-info" title="View" href="#=Link#" target="_blank">
  <i class="icon-external-link white"></i>
</a>

WebParser.Web/Views/ParsedContent/_RatingTemplate.cshtml
<i class="halflings-icon thumbs-up"></i><span>#: GoodRating #</span>
<i class="halflings-icon thumbs-down"></i><span>#: BadRating #</span>
<i class="halflings-icon remove"></i><span>#: OutdateRating #</span>

WebParser.Web/Views/Shared/_Delete.cshtml
<a class="btn btn-danger k-grid-delete js-delete-item" title="Delete">
  <i class="halflings-icon white trash"></i>
</a>

WebParser.Web/Views/Shared/_EditDelete.cshtml
@using WebParser.Web.Utilities

@Html.EditButton()
@Html.Partial("_Delete")

WebParser.Web/Views/Shared/_LeftSideBar.cshtml
@model WebParser.Controllers.ViewModels.Shared.LeftSideBarViewModel
         
<div id="sidebar-left" class="span2">
  <div class="nav-collapse sidebar-nav">
    <ul class="nav nav-tabs nav-stacked main-menu">
      @if (Model.ShowViewerMenuItems)
      {
        <li><a href="@Url.Action("ViewerIndex", "ParsedContent", new {area = string.Empty}, null)"><i class="icon-bar-chart"></i><span class="hidden-tablet">Объявления</span></a></li>
      }
      @if (Model.ShowUserMenuItems)
      {
        <li><a href="@Url.Action("Index", "Dashboard", new {area = string.Empty}, null)"><i class="icon-bar-chart"></i><span class="hidden-tablet">Dashboard</span></a></li>
        <li><a href="@Url.Action("Index", "Site", new {area = string.Empty}, null)"><i class="icon-globe"></i><span class="hidden-tablet"></span>Sites</a></li>
        <li><a href="@Url.Action("Index", "ArticlesGroup", new {area = string.Empty}, null)"><i class="icon-cogs"></i><span class="hidden-tablet">Article Groups</span></a></li>
        <li><a href="@Url.Action("ViewerIndex", "ParsedContent", new {area = string.Empty}, null)"><i class="icon-eye-open"></i><span class="hidden-tablet">Parsed Content</span></a></li>
        <li><a href="@Url.Action("Index", "Help", new {area = ""}, null)"><i class="icon-book"></i><span class="hidden-tablet">Web Api</span></a></li>
        <li><a href="@Url.Action("Index", "BlackListReport", new {area = ""}, null)"><i class="icon-eye-close"></i><span class="hidden-tablet">Black List Report</span></a></li>
        <li><a href="@Url.Action("Index", "WhiteListReport", new {area = ""}, null)"><i class="icon-eye-open"></i><span class="hidden-tablet">White List Report</span></a></li>
        <li><a href="@Url.Action("Index", "BlackAndWhiteArticlesReport", new { area = "" }, null)"><i class="icon-random"></i><span class="hidden-tablet">Black and White Articles</span></a></li>
        <li><a href="@Url.Action("UnwatchedVotesReport", "Vote", new { area = "" }, null)"><i class="icon-random"></i><span class="hidden-tablet">Unwatched Votes</span></a></li>
      }
      @if (Model.ShowAdminMenuItems)
      {
        <li><a href="@Url.Action("Index", "User", new { area = "" }, null)"><i class="icon-group"></i><span class="hidden-tablet">Users</span></a></li>
      }
    </ul>
  </div>
</div>